### ISSUE TITLE
How to generate AUTH_PRIVATE_BASE64 and AUTH_PUBLIC_BASE64 keys

### ISSUE THREAD

**Issue by madcoda9000** [oaktreeapps/admin_panel_cli#18]
Hello,

i've successfully got it running. But authentication fails with the message: SecretOrPrivateKey must be an asymmetric key when using RS256

![image](https://github.com/oaktreeapps/admin_panel_cli/assets/25504739/6b1f36d3-c46f-425a-b98e-89ea68c52c69)

How can i generate such keys?

All the best
Sascha

**Comment by pkhivesara** [comment]
Hello @madcoda9000 Thank you for creating the issue!

You will need to add the generated private and public keys to the backend file here: https://github.com/oaktreeapps/admin_panel_cli#backend

You can try the steps below:

- ``ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key``
- ``openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub``
- ``cat jwtRS256.key``
- ``cat jwtRS256.key.pub``

The above commands will generate the private and public keys, which you will need to convert into base64 format.

Please make sure that you don't add the passphrase!

Feel free to reopen this ticket in case you need more help. Thanks!
